package models

// EvidenceQuote represents a single evidence quote with location and relevance (V5 format)
type EvidenceQuote struct {
	Quote          string `json:"quote"`
	SourceLocation string `json:"source_location"`
	Relevance      string `json:"relevance,omitempty"`
}

// ExtractedFact represents a single extracted fact from a document
type ExtractedFact struct {
	// Core fields (required)
	Claim          string  `json:"claim"`
	SourceDoc      string  `json:"source_doc"`
	SourceLocation string  `json:"source_location"`
	Confidence     float64 `json:"confidence"`

	// Evidence - V5 format (preferred)
	EvidenceQuotes []EvidenceQuote `json:"evidence_quotes,omitempty"`
	// V4 backward compatibility
	EvidenceQuote string `json:"evidence_quote,omitempty"`

	// Chunk tracking
	ChunkID string `json:"chunk_id,omitempty"` // Set at extraction time, verified at load time

	// Fact index - assigned sequentially during extraction and persisted
	// This is the ground truth for fact ordering
	FactIndex int `json:"fact_index,omitempty"`

	// Global index in the facts list (computed at load time for comparison)
	GlobalIndex int `json:"-"` // Not serialized - used to detect mismatches

	// Metadata
	FactType           string            `json:"fact_type,omitempty"`
	ControlFamily      string            `json:"control_family,omitempty"`
	SpecificityScore   float64           `json:"specificity_score,omitempty"`
	Entities           []string          `json:"entities,omitempty"`
	QuantitativeValues []string          `json:"quantitative_values,omitempty"`
	ProcessDetails     map[string]string `json:"process_details,omitempty"`
	SectionContext     string            `json:"section_context,omitempty"`
	RelatedControlIDs  []string          `json:"related_control_ids,omitempty"`
	AutoGenerated      bool              `json:"auto_generated,omitempty"`
}

// GetPrimaryQuote returns the first evidence quote, handling both V4 and V5 formats
func (f *ExtractedFact) GetPrimaryQuote() string {
	if len(f.EvidenceQuotes) > 0 {
		return f.EvidenceQuotes[0].Quote
	}
	return f.EvidenceQuote
}

// GetAllQuotes returns all evidence quotes as strings
func (f *ExtractedFact) GetAllQuotes() []string {
	if len(f.EvidenceQuotes) > 0 {
		quotes := make([]string, len(f.EvidenceQuotes))
		for i, eq := range f.EvidenceQuotes {
			quotes[i] = eq.Quote
		}
		return quotes
	}
	if f.EvidenceQuote != "" {
		return []string{f.EvidenceQuote}
	}
	return nil
}

// NormalizeEvidence converts V4 format to V5 format if needed
func (f *ExtractedFact) NormalizeEvidence() {
	if len(f.EvidenceQuotes) == 0 && f.EvidenceQuote != "" {
		f.EvidenceQuotes = []EvidenceQuote{{
			Quote:          f.EvidenceQuote,
			SourceLocation: f.SourceLocation,
		}}
	}
}

// FactExtractionResult contains facts extracted from a single chunk
type FactExtractionResult struct {
	ChunkID   string          `json:"chunk_id"`
	Document  string          `json:"document"`
	Facts     []ExtractedFact `json:"facts"`
	LineStart int             `json:"line_start"`
	LineEnd   int             `json:"line_end"`
	ChunkText string          `json:"chunk_text,omitempty"` // Original chunk text for source context
}

// ValidationResult contains the result of validating a fact's evidence
type ValidationResult struct {
	IsValid        bool    `json:"is_valid"`
	ErrorMessage   string  `json:"error_message,omitempty"`
	RecoveredQuote string  `json:"recovered_quote,omitempty"`
	MatchRatio     float64 `json:"match_ratio"`
	NearMatch      bool    `json:"near_match"`
}

// Fact type constants
const (
	FactTypeTechnicalControl  = "technical_control"
	FactTypeOrganizational    = "organizational"
	FactTypeProcess           = "process"
	FactTypeMetric            = "metric"
	FactTypeCUEC              = "CUEC"
	FactTypeTestResult        = "test_result"
	FactTypeArchitecture      = "architecture"
	FactTypeCompliance        = "compliance"
	FactTypeExternalReference = "external_reference"
)

// Control family constants
const (
	ControlFamilyAccessControl      = "access_control"
	ControlFamilyEncryption         = "encryption"
	ControlFamilyMonitoring         = "monitoring"
	ControlFamilyBackupRecovery     = "backup_recovery"
	ControlFamilyChangeManagement   = "change_management"
	ControlFamilyIncidentResponse   = "incident_response"
	ControlFamilyNetworkSecurity    = "network_security"
	ControlFamilyPhysicalSecurity   = "physical_security"
	ControlFamilyDataProtection     = "data_protection"
	ControlFamilyVendorManagement   = "vendor_management"
	ControlFamilyRiskManagement     = "risk_management"
	ControlFamilySecurityAwareness  = "security_awareness"
	ControlFamilyAssetManagement    = "asset_management"
	ControlFamilyBusinessContinuity = "business_continuity"
)
